### ISSUE TITLE
"catkin_make" error

### ISSUE THREAD

**Issue by FelicxFoster** [tahsinkose/hector-moveit#4]
Hello, thanks your project. I git clone your code and catkin_make, but it has some errors as follow:

-- Could not find the required component 'moveit_core'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "moveit_core" with
  any of the following names:

    moveit_coreConfig.cmake
    moveit_core-config.cmake

  Add the installation prefix of "moveit_core" to CMAKE_PREFIX_PATH or set
  "moveit_core_DIR" to a directory containing one of the above files.  If
  "moveit_core" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  hector_moveit_exploration/CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/felicx/hector-moveit/build/CMakeFiles/CMakeOutput.log".
See also "/home/felicx/hector-moveit/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

Could you help me, thanks.

**Comment by tahsinkose** [comment]
Sorry for not adding it as dependency. You should do `sudo apt-get install ros-kinetic-moveit*` before  catkin_make. This project depends on MoveIt! framework and it should be installed beforehand.

**Comment by FelicxFoster** [comment]
Thanks for your help, I have solved that problem, but I got another one when I catkin_make:


/home/felicx/hector-moveit/src/hector_moveit_gazebo_plugins/src/fruit_generator.cc: In member function ‘virtual void gazebo::FruitGenerator::Load(gazebo::physics::WorldPtr, sdf::ElementPtr)’:
/home/felicx/hector-moveit/src/hector_moveit_gazebo_plugins/src/fruit_generator.cc:23:32: error: ‘class gazebo::physics::World’ has no member named ‘Models’
         auto models = _parent->Models();
                                ^
/home/felicx/hector-moveit/src/hector_moveit_gazebo_plugins/src/fruit_generator.cc:25:22: error: unable to deduce ‘auto&&’ from ‘models’
         for(auto m : models){
                      ^
hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/build.make:62: recipe for target 'hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/src/fruit_generator.cc.o' failed
make[2]: *** [hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/src/fruit_generator.cc.o] Error 1
CMakeFiles/Makefile2:4369: recipe for target 'hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/all' failed
make[1]: *** [hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[  0%] Linking CXX shared library /home/felicx/hector-moveit/devel/lib/libhector_gazebo_reset_plugin.so
[  0%] Built target hector_gazebo_reset_plugin
[  0%] Linking CXX shared library /home/felicx/hector-moveit/devel/lib/libdiffdrive_plugin_6w.so
[  0%] Linking CXX shared library /home/felicx/hector-moveit/devel/lib/libhector_servo_plugin.so
[  0%] Built target diffdrive_plugin_6w
[  0%] Built target hector_servo_plugin
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed


Could you help me? thanks

**Comment by tahsinkose** [comment]
Closing to isolate problems. New issue is at [here](https://github.com/tahsinkose/hector-moveit/issues/5).

**Comment by Akashleena** [comment]
> sudo apt-get install ros-kinetic-moveit worked for me. Thanks @tahsinkose
