### ISSUE TITLE
Gazebo 7 Incompatibility

### ISSUE THREAD

**Issue by FelicxFoster** [tahsinkose/hector-moveit#5]
Thanks for your help, I have solved my last problem, but I got another one when I catkin_make:

/home/felicx/hector-moveit/src/hector_moveit_gazebo_plugins/src/fruit_generator.cc: In member function ‘virtual void gazebo::FruitGenerator::Load(gazebo::physics::WorldPtr, sdf::ElementPtr)’:
/home/felicx/hector-moveit/src/hector_moveit_gazebo_plugins/src/fruit_generator.cc:23:32: error: ‘class gazebo::physics::World’ has no member named ‘Models’
         auto models = _parent->Models();
                                ^
/home/felicx/hector-moveit/src/hector_moveit_gazebo_plugins/src/fruit_generator.cc:25:22: error: unable to deduce ‘auto&&’ from ‘models’
         for(auto m : models){
                      ^
hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/build.make:62: recipe for target 'hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/src/fruit_generator.cc.o' failed
make[2]: *** [hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/src/fruit_generator.cc.o] Error 1
CMakeFiles/Makefile2:4369: recipe for target 'hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/all' failed
make[1]: *** [hector_moveit_gazebo_plugins/CMakeFiles/fruit_generator.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[  0%] Linking CXX shared library /home/felicx/hector-moveit/devel/lib/libhector_gazebo_reset_plugin.so
[  0%] Built target hector_gazebo_reset_plugin
[  0%] Linking CXX shared library /home/felicx/hector-moveit/devel/lib/libdiffdrive_plugin_6w.so
[  0%] Linking CXX shared library /home/felicx/hector-moveit/devel/lib/libhector_servo_plugin.so
[  0%] Built target diffdrive_plugin_6w
[  0%] Built target hector_servo_plugin
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

Could you help me? thanks

**Comment by tahsinkose** [comment]
[This comment](https://github.com/tahsinkose/hector-moveit/issues/2#issuecomment-425003163) detected this as an issue too. Therefore, I'm changing the header of the issue to Gazebo7 incompatibility. 

I'm using Gazebo9, because of its seamless Actor support. Unfortunately, Gazebo7 was lacking such a feature and I moved to Gazebo9 for my other projects as well. I don't know the status quo of Actors in Gazebo7. If you move to Gazebo9 the problem will be solved.

**Comment by tahsinkose** [comment]
Solution is deliberated in the previous comment. Deprecating the issue for one month inactivity.
