### ISSUE TITLE
use turtlebot model in gazebo

### ISSUE THREAD

**Issue by FelicxFoster** [tahsinkose/hector-moveit#6]
Hello, thanks for your sharing. Have you used the TurtleBot model to replace your UAV model？Could you give me some advice? Thanks.

**Comment by tahsinkose** [comment]
No, I didn't. Actually, this project focuses on aeronautical robots. If you want to have an autonomous mobile robot traversing in the field, you can use [hector_slam](http://wiki.ros.org/hector_slam) or [hector_navigation](https://github.com/tu-darmstadt-ros-pkg/hector_navigation). If you want a ready off the shelf version, there is [turtlebot_exploration_3d](http://wiki.ros.org/turtlebot_exploration_3d) that constructs an Octomap of the environment as Turtlebot navigates.

**Comment by tahsinkose** [comment]
Closing due to timeout.
