### ISSUE TITLE
Issue launching with different world

### ISSUE THREAD

**Issue by furmans** [tahsinkose/hector-moveit#8]
Hello,

I was wondering if it is possible to run hector-moveit with different Gazebo worlds. I am currently trying to launch hector-moveit in Gazebo's empty world, but am having some errors as described below.

I have installed Hector-moveit on Ubuntu 18.04 with ROS Melodic and I tested it using the default launch files that use the garden2 world. I copied empty.world into the hector_moveit_gazebo_worlds/worlds/ directory and modified the orchard_navigation.launch file to launch the empty.world file. I first launch the orchard_navigation.launch file and the output looks normal. I then launch explore.launch and I begin to see different error messages. On hector_explorer node, I get the following error messages indicating that the takeoff has failed. 

[ INFO] [1576012707.894704884, 16.150000000]: Try to start from [19.957798,-0.001118,0.184687]
[ INFO] [1576012707.894814936, 16.150000000]: Try to go to [19.957798,-0.001118,1.000000]
[ WARN] [1576012709.015593266, 16.866000000]: Fail: ABORTED: No motion plan found. No execution attempted.

Hector explorer continues to print
[ INFO] [1576012709.015701858, 16.866000000]: Looking for frontiers

Some error messages from the terminal that launched orchard_navigation.launch:

[ WARN] [1576012708.991452238, 16.864000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[New Thread 0x7fffa67fc700 (LWP 3221)]
[ERROR] [1576012708.991548937, 16.864000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[Thread 0x7fffa6ffd700 (LWP 3220) exited]
[ WARN] [1576012708.993885101, 16.864000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[New Thread 0x7fffa5ffb700 (LWP 3222)]
[ERROR] [1576012708.995369543, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[Thread 0x7fffa77fe700 (LWP 3219) exited]
[ WARN] [1576012708.995873194, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[ERROR] [1576012708.996103529, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[ WARN] [1576012708.996998268, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[ERROR] [1576012708.997056668, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[Thread 0x7fffa5ffb700 (LWP 3222) exited]
[Thread 0x7fffa67fc700 (LWP 3221) exited]
[ WARN] [1576012709.003028451, 16.866000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 0.012239 seconds
[Thread 0x7fffa7fff700 (LWP 3218) exited]
[New Thread 0x7fffa5ffb700 (LWP 3223)]
[ WARN] [1576012709.004734338, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[New Thread 0x7fffa67fc700 (LWP 3224)]
[ERROR] [1576012709.008078972, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[New Thread 0x7fffa6ffd700 (LWP 3225)]
[Thread 0x7fffa5ffb700 (LWP 3223) exited]
[ WARN] [1576012709.008785139, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[ERROR] [1576012709.009018838, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[New Thread 0x7fffa77fe700 (LWP 3226)]
[ WARN] [1576012709.009383756, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[Thread 0x7fffa6ffd700 (LWP 3225) exited]
[ERROR] [1576012709.009443560, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[Thread 0x7fffa67fc700 (LWP 3224) exited]
[ WARN] [1576012709.010554625, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[ERROR] [1576012709.010816722, 16.866000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[ WARN] [1576012709.011027581, 16.866000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 0.007497 seconds
[New Thread 0x7fffa77fe700 (LWP 3227)]
[ WARN] [1576012709.011921324, 16.867000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[ERROR] [1576012709.011979464, 16.867000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[Thread 0x7fffa77fe700 (LWP 3227) exited]
[New Thread 0x7fffa6ffd700 (LWP 3228)]
[Thread 0x7fffa77fe700 (LWP 3226) exited]
[ WARN] [1576012709.013006668, 16.867000000]: DroneBody[RRTConnectkConfigDefault]: Skipping invalid start state (invalid bounds)
[ERROR] [1576012709.014153607, 16.867000000]: DroneBody[RRTConnectkConfigDefault]: Motion planning start tree could not be initialized!
[ WARN] [1576012709.014355866, 16.867000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 0.002745 seconds
[ INFO] [1576012709.014493871, 16.867000000]: Unable to solve the planning problem
[Thread 0x7fffa6ffd700 (LWP 3228) exited]
[ WARN] [1576012711.631622100, 17.556000000]: attitude_controller: No command received for 0.505s, triggering estop

Thank you in advance for any help. 

Sean

**Comment by tahsinkose** [comment]
I've never tried this in another world. Seems the start state are somehow considered as invalid. Could it be that your start state is colliding with the octomap? 

Btw this is a frozen project for more than one year. Thus I might not solve this ASAP, because I got a lot of different assignments in other projects :man_shrugging: Let's see what you can do by investigating the problem of Moveit Motion planner.

**Comment by furmans** [comment]
Thank you for your reply. 

Unfortunately, I am a beginner when it comes to moveit!. Do you have any suggestions for determining if the start state is colliding with octomap? 

Also, I printed out some debug information about start state (using printDirtyInfo, printStateInfo, printStatePositions) and observed that when in the empty world I had some large positive and negative values for velocities and accelerations. When in the garden2 world, the initial velocities and accelerations are zero. I tried using the functions setVariableVelocities and setVariableAccelerations to set the velocity and acceleration states to all zero, but that hasn't fixed my issue. 

Sean

**Comment by tahsinkose** [comment]
> Do you have any suggestions for determining if the start state is colliding with octomap?

You can save the octomap in `.bt` format and later on visualize with [octovis](http://wiki.ros.org/octovis) to understand what is going on. More possibly you can load this octomap with a simple `rosservice` call or a dummy Python node. See [this video](https://www.youtube.com/watch?v=Ib1ISnLlD38). Of course you should do these while running only Rviz, because if you start Gazebo the perception pipeline triggers and octomap might be reset. Therefore just start `moveit_demo.launch` and load the octomap you saved previously. In there you can use interactive markers (see MoveIt tutorials for doing that, pretty beginner stuff :smile: ) and try to figure out what is wrong with the start state.

> observed that when in the empty world I had some large positive and negative values for velocities and accelerations

This is due to an inherent problem of `hector_quadrotor_gazebo_plugins`, namely in the controllers. I did also encounter this while actively developing the project and AFAIR I have written a dedicated Gazebo plugin that is running only in the `garden2.world` that zeroes out velocity and accelerations. Anyways this should not result in the problem of MoveIt :thinking:

**Comment by furmans** [comment]
Thanks again. I will investigate and let you know if I find anything. 

I found out yesterday that if an initial takeoff pose is published to the quadrotor, MoveIt will work properly from that point forward. I wrote an action client that sends the takeoff pose to the pose action server from hector quadrotor package. At that point the explorer node can be launched and Moveit works properly.

**Comment by tahsinkose** [comment]
**Solution:**
> I wrote an action client that sends the takeoff pose to the pose action server from hector quadrotor package. At that point the explorer node can be launched and Moveit works properly
